### ISSUE TITLE
msrvtt_resnext_eco feats

### ISSUE THREAD

**Issue by jssprz** [WingsBrokenAngel/Semantics-AssistedVideoCaptioning#1]
Thank you very much for your code! It has been very useful to me! 
But, when I attempt to load the features in `msrvtt_resnext_eco.npy` file from the link that you included in the README, **ValueError: cannot reshape array of size 13238145 into shape (10000,3584)** occurs. Is it the correct file?

**Comment by jssprz** [comment]
Also, I note you are using a file named `msrvtt_resnext_eco_feats.npy` but the file of your link is named `msrvtt_resnext_eco.npy`

**Comment by WingsBrokenAngel** [comment]
I have checked the files on the cloud and they are correct. Some errors might occur during your downloading. I have computed MD5 and SHA-1 for each file and have inserted them in  README.md. Make sure you have downloaded the `right` files.

Regards!
________________________________
