### ISSUE TITLE
If the test set is used for training tag_net? 

### ISSUE THREAD

**Issue by jwliu-cc** [WingsBrokenAngel/Semantics-AssistedVideoCaptioning#10]
![image](https://user-images.githubusercontent.com/37931056/118475746-35e5b000-b73f-11eb-9a83-07581d2f2493.png)
![image](https://user-images.githubusercontent.com/37931056/118475658-177fb480-b73f-11eb-8e0a-6f772df14801.png)
![image](https://user-images.githubusercontent.com/37931056/118475541-f5863200-b73e-11eb-9570-1c19df329174.png)
I found that train_op is passed to test_step, such that the loss on the test set will be minimized, is this reasonable?

**Comment by WingsBrokenAngel** [comment]
It is probably a mistake. The test set should not be used for training.
