### ISSUE TITLE
Question about MSR-VTT.

### ISSUE THREAD

**Issue by Daic115** [WingsBrokenAngel/Semantics-AssistedVideoCaptioning#3]
Hey man, thanks for your excellent work!  Could you please tell me what resolution you use for MSR-VTT?

**Comment by WingsBrokenAngel** [comment]
Please read my paper. Its hyperlink is in README.md.

**Comment by Daic115** [comment]
I have read it carefully :) , MSR-VTT only provide the youtube urls, some of links are no longer available now. I would be grateful if you could share the clips of MSR-VTT.

**Comment by WingsBrokenAngel** [comment]
I have a copy of MSR-VTT and you will be notified after I upload it to the cloud. The resolution for my MSR-VTT dataset is roughly 360p.

**Comment by Daic115** [comment]
Thanks very much！

**Comment by WingsBrokenAngel** [comment]
@Daic115 Download links for MSR-VTT has been updated in the README.
