### ISSUE TITLE
implementation detail

### ISSUE THREAD

**Issue by alokssingh** [WingsBrokenAngel/Semantics-AssistedVideoCaptioning#4]
Hey @WingsBrokenAngel  nice work thanks for making code publicly for further research.

I have a query regarding implementation, since MSR-VTT have 20 captions for each video. How you have deal with them during?
Did you took random caption for video in each epoch or you have just repeated the features for each caption?
By look the implementation i think you have took all the caption with repeated features. Am I right ?

**Comment by WingsBrokenAngel** [comment]
Yes, you are right.
