### ISSUE TITLE
how to get close mAP as  the newer version 《A Semantics-Assisted Video Captioning Model Trained with Scheduled Sampling》

### ISSUE THREAD

**Issue by AndyMjw** [WingsBrokenAngel/Semantics-AssistedVideoCaptioning#8]
I notice that in latest version of 《A Semantics-Assisted Video Captioning Model Trained with Scheduled Sampling》，mAP has a higher value than in a provisional file,can you share the method to get this result。Thanks。
![image](https://user-images.githubusercontent.com/24457785/92305050-109c8180-efb6-11ea-894e-6335eabbd50e.png)

**Comment by WingsBrokenAngel** [comment]
The semantic detection method is not changed. We just corrected a mistake in calculating the mAP.
